name: Update README

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Update Script
        run: |
          echo "Updating README..."
